---
version: 2

defaults: &defaults
  working_directory: ~/root
  docker:
    - image: 'circleci/node:10'

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run: 
          name: Bootstrap
          command: yarn

      - save_cache:
          name: Save Package Cache
          paths:
           - node_modules
           - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "package.json"  }}

  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run: 
          name: Bootstrap
          command: yarn

      - save_cache:
          name: Save Package Cache
          paths:
           - node_modules
           - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "package.json"  }}

      - run:
          name: Run Test
          command: yarn test

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - test
