name: Deploy to localhost

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Sync to localhost
      - name: Deploy to Server
        run: |
          rsync -avz --delete ./ ~/public_html/
